<?php
session_start();

if (!isset($_SESSION['user_id'])) {
    header("Location: connexion.html");
        exit;
        }

        // Optionnel : récupérer le montant payé, par exemple via GET
        $montant = isset($_GET['amount']) ? (int)$_GET['amount'] : 0;

        ?>

        <!DOCTYPE html>
        <html lang="fr">
        <head>
            <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <title>Paiement réussi - SkyBoost</title>
                        <link rel="stylesheet" href="css/style1.css" />
                            <style>
                                    body {
                                                font-family: Arial, sans-serif;
                                                            background: #f0f4ff;
                                                                        display: flex;
                                                                                    justify-content: center;
                                                                                                align-items: center;
                                                                                                            height: 80vh;
                                                                                                                        margin: 0;
                                                                                                                                }
                                                                                                                                        .success-box {
                                                                                                                                                    background: white;
                                                                                                                                                                padding: 40px 50px;
                                                                                                                                                                            border-radius: 12px;
                                                                                                                                                                                        box-shadow: 0 0 20px rgba(0, 102, 255, 0.2);
                                                                                                                                                                                                    text-align: center;
                                                                                                                                                                                                                max-width: 400px;
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                .success-box h1 {
                                                                                                                                                                                                                                            color: #0066ff;
                                                                                                                                                                                                                                                        margin-bottom: 20px;
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                        .success-box p {
                                                                                                                                                                                                                                                                                    font-size: 18px;
                                                                                                                                                                                                                                                                                                margin-bottom: 30px;
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                .success-box .btn {
                                                                                                                                                                                                                                                                                                                            display: inline-block;
                                                                                                                                                                                                                                                                                                                                        background-color: #0066ff;
                                                                                                                                                                                                                                                                                                                                                    color: white;
                                                                                                                                                                                                                                                                                                                                                                padding: 12px 25px;
                                                                                                                                                                                                                                                                                                                                                                            border-radius: 6px;
                                                                                                                                                                                                                                                                                                                                                                                        text-decoration: none;
                                                                                                                                                                                                                                                                                                                                                                                                    font-weight: bold;
                                                                                                                                                                                                                                                                                                                                                                                                                transition: background-color 0.3s ease;
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                .success-box .btn:hover {
                                                                                                                                                                                                                                                                                                                                                                                                                                            background-color: #004fcc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="success-box">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>Paiement réussi !</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($montant > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Merci pour votre dépôt de <strong><?= htmlspecialchars($montant) ?> FCFA</strong>.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Votre paiement a bien été pris en compte.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="index.php" class="btn">Retour à l'accueil</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>